### ISSUE TITLE
Headers visible when viewing text files

### ISSUE THREAD

**Issue by tzakrajs** [dcwatson/phxd#2]
There are what appear to be headers that are displaying in the Hotline Client view. Able to reproduce on Windows and Mac clients.

[Windows: What I get when I view text files from other common Hotline server](https://puu.sh/DsrAB/1926b8568f.png)
Text representation:
The quick brown fox jumped over the lazy dog.

[Windows: What I get when I view text files from phxd server](https://puu.sh/DsrCs/6216698220.png)
[Mac: What I get when I view text files from phxd server](https://puu.sh/DsrRF/23a2f27013.png)
Text representation:
FILP          INFO     WAMACTEXTttxt
test_file.txt DATA       -The quick brown fox jumped over the lazy dog.

**Comment by tzakrajs** [comment]
It seems like the client is ready to receive data on the socket and is instead given more than it bargained for. I am going to play around and see if I can find a fix for this behavior.

**Comment by dcwatson** [comment]
Just to clarify, this is when viewing in the client, not when downloading? To be honest, we didn't use Hotline much beyond 1.2.3, so I haven't tested some of the "newer" features of 1.9.

**Comment by tzakrajs** [comment]
Yup, the file downloads are fine, it's only when viewing.

**Comment by dcwatson** [comment]
I think that should do the trick. Let me know if this works for you now, and if so I'll push out 1.0.3.
